apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    poolname: group-one-please
spec:
  template:
    metadata:
      labels:
        poolname: group-please
    spec:
      containers:
      - name: conbot
        image: conbot/conbot:latest
        imagePullPolicy: Always
        args:
          - "schema"
          - "-cols 10"
      nodeSelector:
        poolname: workerpool
      restartPolicy: OnFailure
